export const MONSTERS_ACTIONS_TYPE = {
    FETCH_MONSTERS_PENDING: "monsters/FETCH_MONSTERS_PENDING",
    FETCH_MONSTERS_SUCCESS: "monsters/FETCH_MONSTERS_SUCCESS",
    FETCH_MONSTERS_FAILED: "monsters/FETCH_MONSTERS_FAILED"
}